### ISSUE TITLE
Task list to deploy

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#124]
- [x] Add some functionality to handlers
 - [x] disable activation link once it has been used https://github.com/emfoundation/ce100-app/issues/117
 - [x] Archiving an organisation does not affect linked primary user #97
 - [x] Edit user change organisation -> many possible scenarios #100 

- [x] fix broken login

- [x] Bug check.
 - Jobtitle at _No organisation_

- [x] Update google doc on current environment variables #108

- [x] Disable orgs from dropdown that currently have a primary user on front end. Ensure the `no org` option is set to -1 and we deal with selecting an admin. 

- [x] Ensure decent error handling is in place.

- [x] Go over todos and make issues from anything not done

- [x] 1 hour to fix any changes requested by Nelson

- [x] 1 hour to deploy to Heroku

- [x] low priority: fix styling issues:

- [x]  - edit primary user edit button size
- [x]  - css container margin-bottom to padding-bottom (login has whitespace at bottom)
- [x]  - keyboard activated on login makes screen white
- [x] make error message clear to user (hapi error template)
- [x] redirect to login if no token
- [x] add edit user buttons for admin
- [x]  - login logo

- [x] route / should redirect to orgs

- [x] canceling an edit user flow who has no org redirects to /orgs/-1 which should be /orgs

- [x] archive org deactivates the linked user, and removes the link to the organisation, but doesn't remove link to user from the organisations data set - should it?
- [x] Add mock admin data for use in deployment.
- [x] add job title **at organisation** bug
- [x] Fix validation problem

**Comment by JMurphyWeb** [comment]
route / should redirect to orgs

**Comment by JMurphyWeb** [comment]
redirect to login if no token

**Comment by JMurphyWeb** [comment]
make error message clear to user (hapi error template)

**Comment by JMurphyWeb** [comment]
archive org deactivates the linked user, and removes the link to the organisation, but doesn't remove link to user from the organisations data set - should it?

**Comment by JMurphyWeb** [comment]
canceling an edit user flow who has no org redirects to /orgs/-1 which should be /orgs
