### ISSUE TITLE
Review GA event tracking

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#1289]
First step: review what exists in GA tracking and make sure they're picking up real events that still exist.

**Comment by Danwhy** [comment]
All the tags we currently have:

Working:
- [x] GA - Event - Challenge - Edit Tags - Cancel
- [x] GA - Event - Insights - Insight Name
- [x] GA - Event - Org - Edit Tags - Cancel
- [x] GA - Event - People List - Contact Email
- [x] GA - Event - People List - Contact Phone
- [x] GA - Event - Resources - Insight Name
- [x] GA - Event - Org Profile - Contact Email

Not working:
- [ ] GA - Event - Org Profile - Contact Phone
- [ ] GA - Event - Ellipsis Menu - Contact Us
- [ ] GA - Event - Landing Page - Add Challenge
- [ ] GA - Event - Landing Page - See Orgs
- [ ] GA - Event - Landing Page - Update Profile
- [ ] GA - Event - Nav - Challenge
- [ ] GA - Event - Nav - Ellipsis Menu
- [ ] GA - Event - Nav - Explore
- [ ] GA - Event - Nav - Profile
- [ ] GA - Event - Org Profile - Add Challenge
- [ ] GA - Event - Settings - Log out

**Comment by Kimberley-Heath** [comment]
Hi @Danwhy, thanks for taking a look at this! I will list what else we would like to add/ fix/ remove in a separate thread.

**Comment by Danwhy** [comment]
:+1: I've fixed the few that I could see were still there but broken, I'll leave the rest until that issue.

**Comment by asimonw** [comment]
@Danwhy Thanks for that. I'll close this one as the gaps will be dealt with in #1384
