### ISSUE TITLE
On-boarding questions for new users

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#1292]
"As a CE100 contact, I want to specify my interests, so that I can get relevant recommendations on who to talk to or what content to engage with."

For new primary and secondary users, the first screen after the consent forms will ask them to tag themselves with their interests. The interests are sourced from the same topic tags that are used to tag organisations and challenges. The tag selection screen will be the same as the one used on edit org or add/edit challenge.

The interest tags will be stored as part of the user profile.

**Acceptance criteria**
- [x] A screen with copy explaining the benefit of specifying interests, a button to "Choose interests", and a button to "Skip" this step
- [x] If the user clicks on the "Choose interests" button, a topic selection screen (modal on desktop) is displayed
- [x] If the user clicks "Cancel" on the topic selection screen, any changes to the topics are undone and the selection screen closes. Same if the user clicks "Select" on the topic selection screen without actually selecting any tags
- [x] If the user clicks "Select" on the topic selection screen, the selection screen closes and the initial screen is updated to display the selected topics. The buttons at the bottom change to "Edit" and "See matches"
- [x] If the user clicks "Skip" or "See matches" (depending on the state of the screen), they are taken to the next screen. See #1293 

**Mockups**
[Initial state](https://projects.invisionapp.com/share/3DEU1V0A6#/screens/298354399)
[After selection](https://projects.invisionapp.com/share/3DEU1V0A6#/screens/298537769)

[EDIT]
**Desktop mockups**
[Initial state](https://invis.io/DYESHUZW7#/300141937_Onboarding)
[After selection](https://invis.io/DYESHUZW7#/300141934_Onboarding-Tags-Selected)

**Comment by fannyBkane** [comment]
@Danwhy @sophielevens nice! a couple of things I've noticed:

Can the header colour be updated to `navy blue`(as on the mockup)
![screen shot 2018-06-11 at 11 12 36](https://user-images.githubusercontent.com/20577339/41226111-67d5e7b6-6d68-11e8-9624-af8f8b9a78c0.png)

Can the paragraph colour be updated to default dark grey body colour `#333`
![screen shot 2018-06-11 at 11 12 38](https://user-images.githubusercontent.com/20577339/41226103-6188e340-6d68-11e8-931c-c368451f64a5.png)

**Comment by asimonw** [comment]
@Danwhy @sophielevens just to be extra clear, you only need to fix @fannyBkane's first comment https://github.com/emfoundation/ce100-app/issues/1292#issuecomment-396195975 above. Thanks!

**Comment by fannyBkane** [comment]
Great, thanks for @sophielevens !

**Comment by fannyBkane** [comment]
@sophielevens nice! Could you update the H1 blue to #003253 - that should be the navy blue.

Otherwise LGTM!
