### ISSUE TITLE
Personal feed: list of matched people, orgs, challenges and insights

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#1293]
"As a CE100 contact, I want to see a personalised feed of content, so that I can easily find people, orgs, challenges and insights relevant to my interests."

The items which appear in the feed are determined by a matching mechanism similar to the one currently used for challenges, but based on the interests selected in #1292. The ranking order is determined by the number of mutual tags between the user and the other person, org, challenge or insight. We will use the same layout as on the search results page. 

**Acceptance criteria**
- [x] A screen with a list of people, orgs, challenges and insights (in that order), using the search results page layout
- [x] Items to appear are based on the matching and ranking described above. Maximum 10 items per section
- [x] Underneath the list, a "Not what you're looking for?" section with "Edit topics" and "Explore cello" buttons
- [x] The "Edit topics" button opens a topic selection screen, much like in #1292. Editing the topics and clicking "Select" closes the selection screen and immediately shows an updated feed (scrolled back to the top)
- [x] Clicking on "Explore cello" takes the user to the Explore section
- [x] If there are no items in the feed for any of the sections, the copy of this bottom section changes slightly (see mockup) 

**Mockups**
[With matches](https://projects.invisionapp.com/share/3DEU1V0A6#/screens/298354397)
[Without matches](https://projects.invisionapp.com/share/3DEU1V0A6#/screens/299074280)

[Edit]
**Desktop mockups**
[With matches](https://invis.io/DYESHUZW7#/300141936_My_Matches-Matches_Displayed)
[Without matches](https://invis.io/DYESHUZW7#/300141935_My_Matches-No_Matches_Displayed)

**Comment by sophielevens** [comment]
Hi @asimonw, if a user chooses to skip this step would you like the "choose interests" page to show every time they log in? 

Otherwise, we will have to think about including a "do not show me this message again" checkbox within this view. This would mean that they would have to manually navigate to the edit my profile section and add their interests there.

**Comment by asimonw** [comment]
@sophielevens Yes, please just show the "choose interests" page every time they log in as long as they have no interests selected.

If turns out to be frustrating to users, we will build in something along the lines of your suggestion at a later stage.

**Comment by fannyBkane** [comment]
Mobile: Could you make the 'm' of matches lower case, and update the matches icon to the following (just sent to gmail):
![screen shot 2018-06-11 at 10 50 27](https://user-images.githubusercontent.com/20577339/41224822-46c7a10c-6d65-11e8-8d24-004794daee1d.png)

Is there a reason why the text colour here is #000?
![screen shot 2018-06-11 at 10 39 03](https://user-images.githubusercontent.com/20577339/41224179-b9c0c0c8-6d63-11e8-86b9-b3c91d2ecba3.png)

It'd be good to increase the space, between `<ul>` and the header below it, to group categories more effectively, and increase legibility of the list. I understand this is beyond the scope, and that it will affect the search results too, could you advise on whether it should be logged as a separate issue?
![screen shot 2018-06-11 at 10 43 52](https://user-images.githubusercontent.com/20577339/41224752-247e9df8-6d65-11e8-8211-edbc68c7ff35.png)

A question: is there a reason why the headers 'People', 'Organisations', 'Challenges' and 'Insights' use a `<h1> `tag, and the header My matches a `<h2>`?

**Comment by Kimberley-Heath** [comment]
Nothing to add from my point of view, looks good! @asimonw

**Comment by asimonw** [comment]
@Danwhy @sophielevens See Fanny's comments above 👍

**Comment by sophielevens** [comment]
Hi @fannyBkane, thanks for these points, they have all been amended in the following commit 🤓  

I have added space between the <ul>s on the matches page and the search results page. I didn't see the need to open an issue on this point as it was a relatively quick fix 👍

**Comment by fannyBkane** [comment]
Hey @sophie thanks for those changes! A couple of things

The following headers and paragraph seem to have mixed colours. Could you refer to the mobile prototype colours, as follows: Headers #003253 and paragraph #333333?
![screen shot 2018-06-13 at 11 11 27](https://user-images.githubusercontent.com/20577339/41345161-c9d1dafe-6efa-11e8-9718-87e720a24589.png)
![screen shot 2018-06-13 at 11 11 39](https://user-images.githubusercontent.com/20577339/41345162-c9f48d24-6efa-11e8-87d8-64a3dbdb9508.png)
![screen shot 2018-06-13 at 11 11 51](https://user-images.githubusercontent.com/20577339/41345163-ca14841c-6efa-11e8-9467-f7cbc419f497.png)

**Comment by fannyBkane** [comment]
@sophielevens the spacin in the ul looks soo much better thank you!
I've noticed also a bit of uneven spacing in teh message at the bottom. Coudl it be adjusted, mocked up some values below - hope that makes sense... The 'tablet' follows mobile design.
![screen shot 2018-06-13 at 11 28 25](https://user-images.githubusercontent.com/20577339/41345997-214d9640-6efd-11e8-80d9-a7bbf12609e3.png)

**Comment by asimonw** [comment]
@sophielevens note that there are two comments from Fanny to take into account 😄

**Comment by fannyBkane** [comment]
LGTM @sophielevens @asimonw
