### ISSUE TITLE
Issues and changes to be made (post-demo 07/10/2016)

### ISSUE THREAD

**Issue by mk4111** [emfoundation/ce100-app#276]
### Adding a New Org/User flow:
- [ ] Add _upload logo_ functionality to the **Add New Organisation** view, under 'Organisation Name' ( #277 )
- [x] Right after a primary_user activates their acount, redirect them to their **Organisation Profile** view (on login thereafter, /orgs/browse is fine)
- [x] On *Contact List* view, where a user's job_title has not been filled out, we see 'at CompanyName'. 
- [x] On _editting a contact_, route back to the the **Contact List** view (currently routing to their **Organisation Profile**) 
- [x] Change wording on **Browse** view --> 'Select Tags' to 'All Tags' 

- [x] Change URL from /browse to /orgs or /challenges Note need to write up an issue.

### Other Tidbits
- [x] Change wording on **Admin Navbar** --> 'Org' to 'Organisation'
- [x] Change wording 'Contacts' to 'People'
- [x] Copy updates ( #176 ) 
- [x] Fix ```require('tags.json')``` ( #275 )
- [x] Filter own organisation out of *Suggested Matches*.
- [x] 500 error on browse/challenges --> ```error: name of undefined```

### Complete
- [x] Fix input boxes --> textarea ( #188 )

**Comment by mk4111** [comment]
Going to split up the tasks based on user-flow
