### ISSUE TITLE
PG by endpoint

### ISSUE THREAD

**Issue by JMurphyWeb** [emfoundation/ce100-app#366]
This is to get an idea of what queries need to be built by endpoint.

## Key to follow:
-  if a box has an issue number next to it, work has started on it
-  if a box is checked, it has been finished in the plugin (merged into master)
-  ~~if a line is crossed out,~~ it has been integrated into ce100

## General
- [x] ~~/login (post) - people.getByEmail(email, cb)~~ #382

- [x] ~~All routes with auth: people.getById(id, cb)~~ #390

## Challenges

- [x]  'GET',  ~~path: /challenges(?tags=8)~~  - challenges.getAll(cb) #372  and challenges.getByTag(id, cb) #369 
~~( 2hrs to test )~~ `>>` tests included in PR #387  

- [x]  'GET',  ~~path: /challenges/tags~~ - tags.getAllActive(cb) - 2hrs (~~going to change a bit and~~ **add tests** (already integrated))

- [x]  'GET',   ~~path: '/challenges/{challengeId}/tags'~~ - tags.getTagsForEdit('challenges', challengeId, cb) #363 
Edit a new or existing challenge
( 2hrs ) - **Needs to be integrated and tested**.

- [x]  'POST',  ~~path: '/challenges/{challengeId}/tags'~~ - tags.addTags('challenges', challengeId, [array of tags], cb)
( 4hrs ) - Our query needs to be improved (remove old tags then add all new ones), then integrated and tested.
>> unchecked. Reason: addTags method exists, but as described above, need to improve it. Also not yet implemented in this app.

- [x] 'GET',   ~~path: '/challenges/add' - No function needed~~

- [x]  'POST',  path: '/challenges/add' - addChallenge(challengeObject, cb) #373
( 2 hrs ) Integrate and test

- [x]  'GET',   ~~path: '/challenges/{id}/edit'~~ - challenges.getById(id, cb) (attach all tags to challenge) #365 
( 2 hrs ) Integrate and test

- [x]  'POST',  ~~path: '/challenges/{id}/edit'~~ - updateChallenge(challengeObject, id, cb) #374
`UPDATE challenges SET title = 'new  title name', description = 'new description' WHERE id = 1;`
( 4hrs ) Needs writing, adding to plugin, tested in plugin, integrated to app, tested in app

- [x] 'GET'  path: '/challenges/{id}/toggle-archive' - toggleArchive(id, cb)
`UPDATE challenges SET active = NOT active WHERE id = 1;`
( 4hrs ) Needs writing, adding to plugin, tested in plugin, integrated to app, tested in app

## Organisations

  - [x] ~~'GET',  path: '/orgs':~~ #399 
    - [x] Need to amend orgs.getActiveOrgs to orgs.getAll(<active = true>, cb);
    - [x] Need to write orgs.getByTag(<active = true/false>, tagId, cb);
( 1 day ) Both need to be written, tested in plugin, integrated, tested in application
>> Now exists as PR #404

  - [x] 'GET',  ~~path: '/orgs/tags'~~ - tags.getAllActive(cb)
  ( 2 hrs ) ~~Need to integrate and~~ **test**
>> Updated in #414 
  
  - [x] ~~'GET',  path: '/orgs/add'~~ - None needed
  
  - [x] ~~'POST', path: '/orgs/add'~~ - orgs.add(orgObject, cb) #415 
  ( 2rhs ) orgs table only -> need to add logo_url field, integrate and test

  - [x] ~~'GET',  path: '/orgs/{id}'~~ - orgs.getById(id, cb)  #395
  View org details
  ( 4hrs ) **excluding suggested matches** -> Join orgs, challenges, people & tags

  - [x] ~~'GET',  path: '/orgs/{id}/edit'~~ - orgs.getById #405
  Join orgs, tags & people (different permissions for admin & primary)
  ( 4hrs )  

  - [x] ~~'POST', path: '/orgs/{id}/edit'~~ - orgs.update(id, obj, cb) #408
  ( 2hrs )

  - [x] ~~'GET',  path: '/orgs/{id}/toggle-archive'~~ - orgs.toggleArchive(id, cb) #418 
  ( 2 hrs ) similar to challenges toggle archive  

  - [x] 'GET',  ~~path: '/orgs/{id}/tags'~~ - tags.getTagsForEdit('orgs', id, cb) #426
  ( 2 hrs ) this is written, but the 'orgs' version needs to be tested in the plugin, and integrated and tested in the application  

  - [x] 'POST', ~~path: '/orgs/{id}/tags'~~ - tags.addTagsTo('orgs', id, cb) #430
  ( 2hrs ) this is written, but the 'orgs' version needs to be tested in the plugin, and integrated and tested in the application  

## People

- [x] 'GET', path: '/people' - people.getAll(<active = boolean>, cb) #371 
  Returns the list of people with their organisations
  ( 3hrs ) Needs to be amended, integrated and tested
>> Exists as PR #461

- [x] 'GET', path: ~~'/people/add'~~ - orgs.getAll() #442
(active orgs and not already linked to a user -> for drop down) 
https://github.com/postgres-plugin/people/issues/7
 ( 3 hrs ) POSSIBLY DO `GET` `PEOPLE/ID/EDIT` FUNCTION FIRST AND REUSE HERE

- [x] 'POST',  path: '/people/add' - people.add(personObj, cb)
 ( 4hrs )

- [x] 'GET', path: '/people/{id}/edit' - people.getForEdit(id, cb) (get all active orgs for dropdown, some way of referencing whether they have a user attached) 
( 3 hrs ) see /people/add ('get')

- [x] 'POST', path: '/people/{id}/edit' - people.update(personObj, cb)
**unsure** ( added complexity due to linking with organisation )

- [x] 'GET', path: '/people/{id}/toggle-archive' - people.toggleArchive(id, cb)
( 1hr ) same as orgs/id/toggleArchive

- [x] 'GET', path: ~~'/people/activate/{hashedId}'~~ #444
- people.getById(id, cb) (check active & account_activated on user)
( 2hrs )

- [x] 'POST', path: ~~'/people/activate/{hashedId}'~~ - #449
( 2 hrs )

### Some Thoughts

Most of the queries look ok to implement, but without really going in to the handlers, there will be unforeseen problems/side effects. Some queries are quite difficult (**).

##### Generic functions
Generic queries that may be useful not to write out 3 times:
- toggleArchive (orgs, chals, peeps)
- getAll (orgs, chals, peeps)
- update(orgs, chals, peeps)
However it has not always ended up being easy to create generic sql functions, and there is no clear place to put them at the moment. 

##### Active/inactive
We have to re write functions for if admin is viewing and we want both inactive and active or primary user is viewing and we want only active
- we could add an 'active (Boolean)' parameter for each function that needs it, which will adapt the query.
Or we can always get both inactive and active and filter in JS in the handler

**Comment by JMurphyWeb** [comment]
@iteles is this epic"able"?

**Comment by iteles** [comment]
@JMurphyWeb Definitely!

**Comment by iteles** [comment]
@JMurphyWeb Can we please update this issue?

**Comment by JMurphyWeb** [comment]
@iteles should we get this done on monday?
