### ISSUE TITLE
Consolidate visual design and copy

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#656]
The latest visuals can be found in this [new Zeplin project](https://zpl.io/ZOkmLW).

To be discussed how to prioritise the work and most effectively work through the changes together.

----------------

Update: from #656, the priorities for desktop view are: The priorities are still: Explore, profile, walkthrough, people, forms.

**Comment by JMurphyWeb** [comment]
- [ ] [Login](https://github.com/emfoundation/ce100-app/issues/659)
- [ ] [Dashboard](https://github.com/emfoundation/ce100-app/issues/660)
- [ ] [Bottom Nav](https://github.com/emfoundation/ce100-app/issues/661)
- [ ] [Tag Partial](https://github.com/emfoundation/ce100-app/issues/662)

**Comment by JMurphyWeb** [comment]
(rest of) Mobile views:
- [ ] [Explore Insights](https://github.com/emfoundation/ce100-app/issues/689)
- [ ] [Edit org details](https://github.com/emfoundation/ce100-app/issues/690)
- [ ] [Edit user settings](https://github.com/emfoundation/ce100-app/issues/691)
- [ ] [Add challenge](https://github.com/emfoundation/ce100-app/issues/692)
- [ ] [Edit Challenge](https://github.com/emfoundation/ce100-app/issues/693)
- [ ] [Add tags](https://github.com/emfoundation/ce100-app/issues/695)
- [ ] [Burger open](https://github.com/emfoundation/ce100-app/issues/696)
- [ ] [People list](https://github.com/emfoundation/ce100-app/issues/697)

...

Desktop views:

**Comment by JMurphyWeb** [comment]
[Login](https://github.com/emfoundation/ce100-app/issues/698)
[Walkthrough](https://github.com/emfoundation/ce100-app/issues/699)
[Org Details](https://github.com/emfoundation/ce100-app/issues/700)
[Challenge Modal](https://github.com/emfoundation/ce100-app/issues/701)
[Explore Orgs & Chals](https://github.com/emfoundation/ce100-app/issues/702)
[Explore Insights](https://github.com/emfoundation/ce100-app/issues/703)
[Add tags](https://github.com/emfoundation/ce100-app/issues/704)
