### ISSUE TITLE
Improve accessibility for information messages and other elements

### ISSUE THREAD

**Issue by asimonw** [emfoundation/ce100-app#794]
The current light blue over lighter blue contrast of some information messages is not strong enough. 
The edit icon doesn't stand out enough.

- [x] Change body text and headers to grey #333
- [x] Change blue #66D9E0 to grey #40667E
- [x] Change grey #89A0AE to #40667E across the app:
- [x] Change edit icon colour to #40667E 
- [x] Change select tag/parent tag colour to #40667E https://zpl.io/Z1QNlvL
- [x] Change tags background colour #40667E and remove border colour
- [x] Change underlines to no underlines in profile/contact/ get in touch https://zpl.io/ZKA7lv

**Comment by fannyBkane** [comment]
- Change body text and headers to grey #333
- Change blue #66D9E0 to grey #40667E
>>>example: https://staging-ce100-emf.herokuapp.com/people/3/edit
![screen shot 2017-05-11 at 11 09 38](https://cloud.githubusercontent.com/assets/20577339/25944208/60e353c8-363a-11e7-8fd9-744b2f7ae63c.png)
- Change grey #89A0AE to #40667E across the app:
   - Change edit icon colour to #40667E 
https://staging-ce100-emf.herokuapp.com/orgs/1
![screen shot 2017-05-11 at 11 29 08](https://cloud.githubusercontent.com/assets/20577339/25944976/1d3a8558-363d-11e7-8690-5a19738773b2.png)
- Change select tag/parent tag colour to #40667E https://zpl.io/Z1QNlvL
- Change tags background colour #40667E and remove border colour
- Change underlines to no underlines in profile/contact/ get in touch https://zpl.io/ZKA7lv

**Comment by asimonw** [comment]
Added checklist of all items mentioned by @fannyBkane to the top comment.

**Comment by asimonw** [comment]
@harrygfox It looks like the tags haven't been changed to have a dark background on any of the tag selection screens (in the forms and in Explore), only on the profile and challenge cards. Could the ones on the tag selection screens also be changed for consistency? 

Also, on profile and challenge screens, the cursor doesn't change to a pointer on hover.

The rest looks good to me, but @fannyBkane could you also have a look?

**Comment by sohilpandya** [comment]
Hi @asimonw,

Could you please direct me to the forms where the colours have not been changed yet? I am unsure which form you are talking about. 

Thanks! 😄

**Comment by asimonw** [comment]
@sohilpandya There are three places where the tag selection screen shows up:
* Explore -> All tags
* Edit Profile -> Edit tags
* Edit challenge -> Edit tags

For instance here the tags still have white backgrounds:
<img width="694" alt="screen shot 2017-05-19 at 18 46 37" src="https://cloud.githubusercontent.com/assets/15235804/26258114/8e239b38-3cc3-11e7-88d1-fc6fbd105b2e.png">

**Comment by sohilpandya** [comment]
@asimonw I'm unsure what you'd like here as currenlty this is how it looks:

pre-selection:
<img width="495" alt="screen shot 2017-05-19 at 17 55 13" src="https://cloud.githubusercontent.com/assets/2305591/26258376/63bb10e4-3cbc-11e7-8d57-328d136b66fb.png">
post-selection:
<img width="480" alt="screen shot 2017-05-19 at 17 55 18" src="https://cloud.githubusercontent.com/assets/2305591/26258380/69b05d06-3cbc-11e7-962c-1391f7c95528.png">

If we were to change the color to #40667e then both the pre and post colors will be the same. Is that what you would like? 

Sorry if I've completely misunderstood something here. 😟

**Comment by asimonw** [comment]
@sohilpandya You're so right! Can't believe I didn't think of that. I guess that the fact that the selected ones do have the same colour as the tags in the rest of the app is actually quite consistent.

I'm changing this back to `please-test`, disregard my comments above!

So, @fannyBkane would this be fine to close?

**Comment by sohilpandya** [comment]
@asimonw thanks! 👍

**Comment by fannyBkane** [comment]
@sohilpandya would it be ok to change the tag (text) colour to #40667e?
Once that's done it is fine to close @asimonw thanks.

**Comment by SimonLab** [comment]
The color text of the tags has been update, let us know if it looks ok @fannyBkane :+1:

**Comment by fannyBkane** [comment]
All good! Thanks @SimonLab @asimonw fine to close this issue, thanks :)
